#!/bin/bash
#author: kavinyao<kavinyao@gmail.com>
#license: GPLv2

# `vigor` is vi + grep
# It recursively searches for the given string and prints a list of matching files, each with a number.
# You can open the file you want with file number, either positive or negative (from bottom).

LINE_CHARACTER_LIMIT=240

if [ $# -lt 1 ]; then
    echo "vigor: recursive grep search and open specified one with vi"
    echo "Usage: vigor string_to_search [-s] [line]"
    exit 1
fi

# store search result
res=$(grep --color=always "$1" -nr .)
# no -n flag, otherwise would result in one less line for wc
total_lines=$(echo "$res" | wc -l | tr -d ' ')
# echo "Total lines: $total_lines"
width=${#total_lines}

if [ $# -eq 1 ]; then
    # output directly
    echo -n "$res" | nl -w $width -s '] ' | sed 's/^/[/'
    exit 0
fi

if [ "$2" = "-s" ]; then
    # strip ridiculously long lines
    res=$(echo -n "$res" | awk -v limit=$LINE_CHARACTER_LIMIT $'{if(length($0) <= limit) print}')
    # no -n, same reason as above
    total_lines=$(echo "$res" | wc -l | tr -d ' ')
    # echo "Total lines: $total_lines"
    width=${#total_lines}

    if [ $# -eq 2 ]; then
        # no more argument, output now
        echo -n "$res" | nl -w $width -s '] ' | sed 's/^/[/'
        exit 0
    fi
fi

# in this case the last argument should be the line number
line_no="${@: -1}"
if [ $line_no -le 0 ]; then
    # the last n-th file
    # convert to the first n-th
    line_no=$(($total_lines+$line_no+1))
fi

# echo "Will open [$line_no]"
line=$(echo -n "$res" | sed -n "$line_no"p | awk -F: '{print $1" "$2}')
if [ -z "$line" ]; then
    echo "No result found."
    exit 1
fi

# extract file name and line number
filename=${line% *}
line_number=${line##* }

echo "opening $filename [$line_number]"
vi $filename +$line_number
